default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["DB_HOST"]%>
  port: <%= ENV["DB_PORT"]%>
  username: <%= ENV["DB_USERNAME"]%>
  password: <%= ENV["DB_PASSWORD"]%>
  database: <%= ENV["DB_NAME"]%>

test:
  <<: *default
  host: <%= ENV["DB_HOST"]%>
  port: <%= ENV["DB_PORT"]%>
  username: <%= ENV["DB_USERNAME"]%>
  password: <%= ENV["DB_PASSWORD"]%>
  database: <%= ENV["DB_NAME"]%>

production:
  <<: *default
  host: <%= ENV["DB_HOST"]%>
  port: <%= ENV["DB_PORT"]%>
  username: <%= ENV["DB_USERNAME"]%>
  password: <%= ENV["DB_PASSWORD"]%>
  database: <%= ENV["DB_NAME"]%>
